Typescript Compile Errors
So the way my application is set up is to utilize typings for typescript
components.  This means that my typings files get loaded from the
typings directory at the root of my application.  When I installed
hammerjs, the instructions had me install the typings files inside of
the npm @types package and then point my tsconfig file to use that
directory.  However since I also had the hammerjs typescript definitions
installed inside of the typings directory, when I would compile I would
recieve 'hammerjs error TS2300: Duplicate identifier' errors.