Bugfix mat Select Missing Module
Was recieving the error:
Error: No value accessor for form control with name:
Turns out I needed to import MatSelectModule